version: '3'

services:
  interface:
    build: .
    container_name: tenzor_interface
    volumes:
      - .:/usr/src/app
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdb_data:/var/lib/postgresql/data/

volumes:
  pgdb_data: